[package]
name = "delay-write"
version = "0.1.0"
edition = "2021"

[lib]
name = "delay_write"
crate-type = ["cdylib"]

[dependencies]
ffgl-core = { workspace = true }
gl = { workspace = true }
gl_loader = { workspace = true }
tracing = { workspace = true }
pluglib = { path = "../pluglib" }
delay-dsp = { path = "../delay-dsp" }
